language: python
python:
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - pip install codecov
  - pip install coveralls

# command to run tests
script: xvfb-run --server-args="-screen 0 1024x768x24" nosetests --with-coverage --cover-package=cauldron

after_success:
    - codecov
    - coveralls
