 version: '3'
 services:
   app:
     build: .
     container_name: cauldron_app
     volumes:
       - .:/cauldron
     ports:
       - "5010:5010"
     stdin_open: true
     tty: true
     entrypoint: /bin/bash
