package:
    name: cauldron
    version: "0.0.16"

build:
    number: 1
    noarch_python: True

source:
  fn: cauldron-notebook-0.0.16.tar.gz
  url: https://pypi.python.org/packages/02/fa/5716cf56b94a04e3dae474fcdd32b97e4b01a8f78031bbd7332b51b74ebe/cauldron-notebook-0.0.16.tar.gz
  md5: 4ae63397d1092e5ed65dbd69f0bcc91f

requirements:
  build:
    - python
    - pandas
    - numpy
    - jinja2
    - markdown
    - pygments
    - beautifulsoup4
    - flask

  run:
    - python
    - numpy
    - pandas
    - jinja2
    - markdown
    - pygments
    - beautifulsoup4
    - flask

test:
  imports:
    - cauldron

about:
  home: https://github.com/sernst/cauldron
  license: MIT
  license_file: LICENSE
