package:
    name: cauldron
    version: "0.0.7"

build:
    number: 1
    noarch_python: True

source:
  fn: cauldron-notebook-0.0.7.tar.gz
  url: https://pypi.python.org/packages/b6/ea/e26537446fc5b5b921e9d8e68fa251839ee3fca9b8a6fe836b802237a210/cauldron-notebook-0.0.7.tar.gz#md5=d8e134eba413a39bb87a930a46e7f027
  md5: d8e134eba413a39bb87a930a46e7f027

requirements:
  build:
    - python
    - pandas
    - numpy
    - jinja2
    - markdown
    - pygments
    - beautifulsoup4
    - flask

  run:
    - python
    - numpy
    - pandas
    - jinja2
    - markdown
    - pygments
    - beautifulsoup4
    - flask

test:
  imports:
    - cauldron

about:
  home: https://github.com/sernst/cauldron
  license: MIT
  license_file: LICENSE
