package:
    name: cauldron
    version: "0.0.14"

build:
    number: 1
    noarch_python: True

source:
  fn: cauldron-notebook-0.0.14.tar.gz
  url: https://pypi.python.org/packages/fa/a3/690febf82f8b0dc4a507069107cd13225599deb2649e8af6e6020aa12093/cauldron-notebook-0.0.14.tar.gz
  md5: 46f29e80d66e444332c8f0601b5bdf4d

requirements:
  build:
    - python
    - pandas
    - numpy
    - jinja2
    - markdown
    - pygments
    - beautifulsoup4
    - flask

  run:
    - python
    - numpy
    - pandas
    - jinja2
    - markdown
    - pygments
    - beautifulsoup4
    - flask

test:
  imports:
    - cauldron

about:
  home: https://github.com/sernst/cauldron
  license: MIT
  license_file: LICENSE
