package:
    name: cauldron
    version: "0.0.10"

build:
    number: 1
    noarch_python: True

source:
  fn: cauldron-notebook-0.0.10.tar.gz
  url: https://pypi.python.org/packages/c3/84/f997ab72e49f16e4ac5cebb47187a78dd9f3f7945fb52be6df3a5ec27c98/cauldron-notebook-0.0.10.tar.gz
  md5: 0abaa66fb1c491a0dab213d618af7a9b

requirements:
  build:
    - python
    - pandas
    - numpy
    - jinja2
    - markdown
    - pygments
    - beautifulsoup4
    - flask

  run:
    - python
    - numpy
    - pandas
    - jinja2
    - markdown
    - pygments
    - beautifulsoup4
    - flask

test:
  imports:
    - cauldron

about:
  home: https://github.com/sernst/cauldron
  license: MIT
  license_file: LICENSE
