package:
    name: cauldron
    version: "0.0.9"

build:
    number: 1
    noarch_python: True

source:
  fn: cauldron-notebook-0.0.9.tar.gz
  url: https://pypi.python.org/packages/3f/35/3bf17f95ce6d13dc07e965ab02237c9bdbd617bd7cd481dd16de23f38049/cauldron-notebook-0.0.9.tar.gz#md5=39593f55b52ff6c475a306840d453892
  md5: 39593f55b52ff6c475a306840d453892

requirements:
  build:
    - python
    - pandas
    - numpy
    - jinja2
    - markdown
    - pygments
    - beautifulsoup4
    - flask

  run:
    - python
    - numpy
    - pandas
    - jinja2
    - markdown
    - pygments
    - beautifulsoup4
    - flask

test:
  imports:
    - cauldron

about:
  home: https://github.com/sernst/cauldron
  license: MIT
  license_file: LICENSE
