package:
    name: cauldron
    version: "0.0.13"

build:
    number: 1
    noarch_python: True

source:
  fn: cauldron-notebook-0.0.13.tar.gz
  url: https://pypi.python.org/packages/51/02/3597da1d053fb475a48e93bc1f7c9b871876b5493dd5a9269bfe2b3b284a/cauldron-notebook-0.0.13.tar.gz
  md5: 24763a1fc3eb1c2072fbfc7bd5a37540

requirements:
  build:
    - python
    - pandas
    - numpy
    - jinja2
    - markdown
    - pygments
    - beautifulsoup4
    - flask

  run:
    - python
    - numpy
    - pandas
    - jinja2
    - markdown
    - pygments
    - beautifulsoup4
    - flask

test:
  imports:
    - cauldron

about:
  home: https://github.com/sernst/cauldron
  license: MIT
  license_file: LICENSE
