package:
    name: cauldron
    version: "0.0.8"

build:
    number: 1
    noarch_python: True

source:
  fn: cauldron-notebook-0.0.8.tar.gz
  url: https://pypi.python.org/packages/32/e5/3b9a59f38dd78ec1e5be6bdcc77f8402e6f43c94ac1584303487fa477109/cauldron-notebook-0.0.8.tar.gz#md5=2e7f20c7281595c99e7429983d30bb57
  md5: 2e7f20c7281595c99e7429983d30bb57

requirements:
  build:
    - python
    - pandas
    - numpy
    - jinja2
    - markdown
    - pygments
    - beautifulsoup4
    - flask

  run:
    - python
    - numpy
    - pandas
    - jinja2
    - markdown
    - pygments
    - beautifulsoup4
    - flask

test:
  imports:
    - cauldron

about:
  home: https://github.com/sernst/cauldron
  license: MIT
  license_file: LICENSE
