package:
    name: cauldron
    version: "0.0.6"

build:
    number: 1
    noarch_python: True

source:
  fn: cauldron-notebook-0.0.6.tar.gz
  url: https://pypi.python.org/packages/39/67/498d5abe30ec1a60a948e18e53b8bf26118f1d123a616b4cb819b39ede04/cauldron-notebook-0.0.6.tar.gz
  md5: 7016fbcff98137e758d226ce2c81d622

requirements:
  build:
    - python
    - pandas
    - numpy
    - jinja2
    - markdown
    - pygments
    - beautifulsoup4
    - flask

  run:
    - python
    - numpy
    - pandas
    - jinja2
    - markdown
    - pygments
    - beautifulsoup4
    - flask

test:
  imports:
    - cauldron

about:
  home: https://github.com/sernst/cauldron
  license: MIT
  license_file: LICENSE
