package:
    name: cauldron
    version: "0.0.12"

build:
    number: 1
    noarch_python: True

source:
  fn: cauldron-notebook-0.0.12.tar.gz
  url: https://pypi.python.org/packages/f0/d4/4fbe8039bb1ad9736297e1fd85e480aa0e3bca44f0daf390a21fb5f1763c/cauldron-notebook-0.0.12.tar.gz
  md5: b3bb92394661a0cce239aebcac94a84b

requirements:
  build:
    - python
    - pandas
    - numpy
    - jinja2
    - markdown
    - pygments
    - beautifulsoup4
    - flask

  run:
    - python
    - numpy
    - pandas
    - jinja2
    - markdown
    - pygments
    - beautifulsoup4
    - flask

test:
  imports:
    - cauldron

about:
  home: https://github.com/sernst/cauldron
  license: MIT
  license_file: LICENSE
