package:
    name: cauldron
    version: "0.0.4"

build:
    number: 1
    noarch_python: True

source:
    git_rev: "v0.0.4"
    git_url: https://github.com/sernst/cauldron.git

requirements:
  build:
    - python
    - pandas
    - numpy
    - jinja2
    - markdown
    - pygments
    - beautifulsoup4
    - flask

  run:
    - python
    - numpy
    - pandas
    - jinja2
    - markdown
    - pygments
    - pyquery
    - flask

test:
  imports:
    - cauldron

about:
  home: https://github.com/sernst/cauldron
  license: MIT
  license_file: LICENSE
