package:
    name: cauldron
    version: "0.0.11"

build:
    number: 1
    noarch_python: True

source:
  fn: cauldron-notebook-0.0.11.tar.gz
  url: https://pypi.python.org/packages/15/d4/4493a105209b7184d3b82dff1196cb2353536262623147f577bcb4ad1f87/cauldron-notebook-0.0.11.tar.gz
  md5: c3a46df988077d16f94307975e15c72a

requirements:
  build:
    - python
    - pandas
    - numpy
    - jinja2
    - markdown
    - pygments
    - beautifulsoup4
    - flask

  run:
    - python
    - numpy
    - pandas
    - jinja2
    - markdown
    - pygments
    - beautifulsoup4
    - flask

test:
  imports:
    - cauldron

about:
  home: https://github.com/sernst/cauldron
  license: MIT
  license_file: LICENSE
