package:
    name: cauldron
    version: "0.0.15"

build:
    number: 1
    noarch_python: True

source:
  fn: cauldron-notebook-0.0.15.tar.gz
  url: https://pypi.python.org/packages/67/4d/b198f17bfa264ea41f266f6bc8ba6bc2f47d5e54d805acabbf1590b3fe60/cauldron-notebook-0.0.15.tar.gz
  md5: 3fb7d83ed40e4fe00c558121959ab1c6

requirements:
  build:
    - python
    - pandas
    - numpy
    - jinja2
    - markdown
    - pygments
    - beautifulsoup4
    - flask

  run:
    - python
    - numpy
    - pandas
    - jinja2
    - markdown
    - pygments
    - beautifulsoup4
    - flask

test:
  imports:
    - cauldron

about:
  home: https://github.com/sernst/cauldron
  license: MIT
  license_file: LICENSE
